name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # Runs every time you push to main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Image
# Replace 'yourusername' with your actual Docker Hub username below
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/pokemon-app:latest

    - name: Run Docker Container (Test)
      run: |
        docker run -d -p 8000:8000 --name pokemon-container pokemon-app:latest
        sleep 5
        curl --silent --fail http://localhost:8000 || exit 1
